version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://flaskuser:flaskpassword@db:5432/flaskdb
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
